<?php

namespace Amsgames\LaravelShop\Gateways;

/**
 * This file is part of LaravelShop,
 * A shop solution for Laravel.
 *
 * @author Alejandro Mostajo
 * @copyright Amsgames, LLC
 * @license MIT
 * @package Amsgames\LaravelShop
 */

use Log;
use Amsgames\LaravelShop\Core\PaymentGateway;

class GatewayPass extends PaymentGateway
{
    /**
     * Called on cart checkout.
     *
     * @param Order $order Order.
     */
    public function onCheckout($cart)
    {
    	//Log::debug('Gateway:: onCheckout');
    	//Log::debug($cart);
    }

    /**
     * Called by shop to charge order's amount.
     *
     * @param Order $order Order.
     *
     * @return bool
     */
    public function onCharge($order)
    {
    	//Log::debug('Gateway:: onCharge');
    	//Log::debug($order);
    	return true;
    }

    /**
     * Returns the transaction ID generated by the gateway.
     * i.e. PayPal's transaction ID.
     *
     * @return mixed
     */
    public function getTransactionId()
    {
    	return time();
    }

    /**
     * Returns a 1024 length string with extra detail of transaction.
     *
     * @return string
     */
    public function getTransactionDetail()
    {
    	return;
    }
}