<?php

namespace Amsgames\LaravelShop\Contracts;

/**
 * This file is part of LaravelShop,
 * A shop solution for Laravel.
 *
 * @author Alejandro Mostajo
 * @copyright Amsgames, LLC
 * @license MIT
 * @package Amsgames\LaravelShop
 */

interface PaymentGatewayInterface
{
    /**
     * Constructor.
     */
    public function __construct($id = '');
    
    /**
     * Called on cart checkout.
     *
     * @param Order $order Order.
     */
    public function onCheckout($cart);

    /**
     * Called by shop to charge order's amount.
     *
     * @param Order $order Order.
     *
     * @return bool
     */
    public function onCharge($order);

    /**
     * Returns the transaction ID generated by the gateway.
     * i.e. PayPal's transaction ID.
     *
     * @return mixed
     */
    public function getTransactionId();

    /**
     * Returns a 1024 length string with extra detail of transaction.
     *
     * @return string
     */
    public function getTransactionDetail();

}